#!/usr/bin/env python3

import os
import sys

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(project_root)

from Bazaar.Referee.game_state import GameState
import json

def main():
    input_data = json.loads(sys.stdin.read())

    game_state = GameState.deserialize(input_data)
    next_turn = game_state.extract_turnstate()
    output_data = next_turn.serialize()

    json.dump(output_data, sys.stdout)

if __name__ == "__main__":
    main()
