#!/usr/bin/env python3.9

import os
import sys
import importlib

sys.stdout.reconfigure(encoding='utf-8')
os.environ["PYGAME_HIDE_SUPPORT_PROMPT"] = "1"

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(project_root)

module = importlib.import_module("8.xgames_blogic")

if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "--show":
        module.main(True)
    else:
        module.main(False)