#!/usr/bin/env python3.9

import os
import sys
import ijson

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(project_root)

sys.stdout.reconfigure(encoding='utf-8')
os.environ["PYGAME_HIDE_SUPPORT_PROMPT"] = "1"

from Bazaar.Client.client import Client
from Bazaar.Player.mechanism import deserialize_actors

def main(port: int):
    json_values = []

    for obj in ijson.items(sys.stdin.buffer, "", buf_size=1, multiple_values=True):
        json_values.append(obj)

    actors = deserialize_actors(json_values[0])

    for actor in actors:
        client = Client()
        client.start_client(actor.name, actor.policy, port)

if __name__ == "__main__":
    if len(sys.argv) == 2:
        main(int(sys.argv[1]))